### ISSUE TITLE
Circle CI fails when the PR is from an external contributor

### ISSUE THREAD

**Issue by hardlydifficult** [unlock-protocol/unlock#1796]
**Describe the bug**
If an external contributor creates a PR, the PR build from Circle CI fails.

**To Reproduce**
1. Fork Unlock
2. Create a branch in the forked repo
3. Create a PR merging the branch into Unlock

**Additional context**
I use this process, so all my recent PRs are impacted.  For example: #1756

@julien51 started looking at this, but figured we should get a corresponding issue open

**Comment by julien51** [comment]
Dammit. I am so sorry about that. Looking into it right now.

**Comment by julien51** [comment]
Actually I am waiting to hear from the Circle team on this one (emailed them about it on wed...)

**Comment by julien51** [comment]
Hey @hardlydifficult . I checked your latest PR (https://github.com/unlock-protocol/unlock/pull/1969/checks?check_run_id=74681240) and it looks like Circle checks passed just fine.  

So I am closing this because I think this is fixed. Feel free to re-open if not!

**Comment by hardlydifficult** [comment]
It still fails: https://github.com/unlock-protocol/unlock/pull/2022

Sorry I had forgotten to mention that I switch to use the standard process instead.

**Comment by hardlydifficult** [comment]
Oh the CI links seem to disappear from the PR when I close it.  See https://circleci.com/gh/unlock-protocol/unlock/6828

**Comment by julien51** [comment]
hooo ok, let me look into this!

**Comment by julien51** [comment]
So, the problem is that we cannot seem to be able to push temporary images to docker because of course we are missing docker credentials on this one.

So I will refactor our process to see if we can skip the step where we push the temporary built image to docker and rather use a local cache.

**Comment by julien51** [comment]
We now have Chromatic available on forked PRs.
The next step is to disable publishing to Netlify which can be done by skipping it when $CIRCLE_PR_USERNAME is set.
